version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    runtime: nvidia # GPU Maxwell
    shm_size: "128mb" # Video buffer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config.yml:/config/config.yml
      - ./frigate/media:/media/frigate
      - type: tmpfs # Use memory instead of SSD
        target: /tmp/cache
        tmpfs:
          size: 512000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP
      - "8555:8555/tcp" # WebRTC
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "${FRIGATE_RTSP_PASSWORD}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      DAHUA_USER: "${DAHUA_USER}"
      DAHUA_PASSWORD: "${DAHUA_PASSWORD}"
      DAHUA_IP: "${DAHUA_IP}"
