mqtt:
  # Runs inside Docker network and hostname can used
  host: mosquitto 
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

detectors:
  tensorrt:
    type: tensorrt
    device: 0 # Jetson GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt # Frigate model cache
  width: 320
  height: 320

objects:
  track:
    - person
    - dog

cameras:
  camara_principal: # Descriptive names but no must follow yaml syntaxis
    ffmpeg:
      inputs:
        # Secondary stream (low res): ML model analyzer
        - path: rtsp://{FRIGATE_DAHUA_USER}:{FRIGATE_DAHUA_PASSWORD}@{FRIGATE_DAHUA_IP}:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Primary stream (hi res): exlusive to save clips
        - path: rtsp://{FRIGATE_DAHUA_USER}:{FRIGATE_DAHUA_PASSWORD}@{FRIGATE_DAHUA_IP}:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      # Ajusta esto a la resolución real de tu flujo secundario (usualmente 640x480 o 1280x720 en Dahua)
      width: 320 
      height: 320
      fps: 5 # 5 FPS sweet spot for Nano
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
    snapshots:
      enabled: true
      bounding_box: true
